@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 180
skinparam sequenceParticipant bold
title  Immunisation Update Request
participant "ISM" as AA #CornflowerBlue
participant "ImmSOT" as A #CornflowerBlue
participant "Orchestration" as B #CornflowerBlue
participant "Healthlink Air Broker" as C #CornflowerBlue
participant "PMS" as D #CornflowerBlue
|||
activate AA
AA -> A: POST [base]/Immunization
activate A
A -> A: Create Immunisation record 
A -[dashed]-> AA:  200 Response 
deactivate A

A -> A: construct Immunisation Update Request message (empty destination)
activate A
deactivate AA

A -> B: POST [base]/$process-message

activate B
|||
B -> B: Determine destinations
B -> B: Populate Patient resource
B -> B: Get facility id for  each destination
|||
B -> C: POST [base]/$process-message
activate C
C -> C:  transform to HL7 VXU^V04
C -> D: VXU^V04 request
C -[dashed]-> B:  202 Response 
B -[dashed]-> A: 202 Response 
deactivate B
|||
deactivate C
deactivate A
|||
@enduml