@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 180
skinparam sequenceParticipant bold
title "Create Immunisation using\nlegacy HL7 v2.0 messaging\nv1"
actor "Integrating application user" as user #CornflowerBlue
participant "Integrating application\n(PMS)" as integrating_app #CornflowerBlue
box "Healthlink"
  participant "AIR Broker\n<HL7v2>-<FHIR>" as broker #CornflowerBlue
end box
box "AIR"
  participant "Immunisation API\n<FHIR>" as air_pub_api #CornflowerBlue
end box

user -> integrating_app: Enter immunisation
integrating_app -> broker: VXU^V04 request
alt Not Authorised
  broker -> integrating_app: ACK^V04 NACK response
end
broker -> broker: Transform\nto FHIR
alt Encountered an Error
  broker -> integrating_app: ACK^V04 NACK response
end

group FHIR API Flow
  broker -> air_pub_api: POST [FHIR Bundle]
  activate air_pub_api
  air_pub_api -> air_pub_api: (process)
  air_pub_api -> broker: Response
  deactivate air_pub_api
end
broker -> broker: Transform\nto HL7 ACK^V04
alt Encountered an Error] or\n[Rejected
  broker -> integrating_app: ACK^V04 NACK response
end
broker -> integrating_app: ACK^V04 ACK response (success)
integrating_app -> user: Display outcome
@enduml