default:
  tags:
    - azure

image: registry.gitlab.com/healthnz-prm/air/air-api-orca/orca:0.6

stages:
  - build-prepare
  - build
  - release
  - build-pages
  - deploy
  - post-release

variables:
  RELEASE:
    value: "false"
    description: "Set to true in order to build a new release."
  RELEASE_MAJOR:
    value: "false"
    description: "If true then a major release will be built. Only applies if RELEASE=true and the release is made from the main branch."
  API_VERSION: "v2"
  PUBLISH_SCRIPTS_GIT_REPO: "air-api-fhir-ig-v2"
  CI_DEBUG_TRACE: "true"

ig-build-prepare:
  stage: build-prepare
  rules:
    - if: $CI_COMMIT_REF_NAME == "main" || $CI_COMMIT_REF_NAME =~ /^release\/.+/
  script:
    - ./ci-scripts/pre-build.sh
  artifacts:
    paths:
      - sushi-config.yaml
    reports:
      dotenv: version.env
    expire_in: 1 week

build-ig:
  stage: build
  variables:
    KUBERNETES_CPU_REQUEST: "2"
    KUBERNETES_CPU_LIMIT: "4"
    KUBERNETES_MEMORY_REQUEST: "4G"
    KUBERNETES_MEMORY_LIMIT: "4G"
  script:
    - ./_updatePublisher.sh -y
    - ./build-ig.sh
    - ./transform_to_marketplace_spec.sh
  artifacts:
    paths:
      - output
      - sushi-config.yaml
    expire_in: 1 week

ig-release:
  stage: release
  rules:
    - if: $RELEASE == "true"
  script:
    - set -euxo pipefail
    - ./ci-scripts/create-release.sh

build-web-pages-archive:
  image: alpine:latest
  stage: build-pages
  rules:
  - if: $RELEASE == "true"
  before_script:
    - apk add zip curl yq
  script:
    - (cd output; zip -r "../web-pages.zip" .)
    - PUBLISH_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${API_VERSION}/${MVN_IG_VERSION}/web-pages.zip"
    - echo "Uploading ${PUBLISH_URL}"
    - >
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file web-pages.zip "${PUBLISH_URL}"
  artifacts:
    name: "${CI_COMMIT_REF_NAME}-web-pages"
    paths:
      - web-pages.zip
    expire_in: 1 month

mvn-deploy-package:
  image: maven:3-amazoncorretto-17
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == "main" || $CI_COMMIT_REF_NAME =~ /^release\/.+/
  cache:
    paths:
      - .m2/repository
  script:
    # Very annoying but maven complains there is a missing pom if we turn this into a multi line command...
    - mvn deploy:deploy-file -s ci_settings.xml -Dfile=output/package.tgz -DrepositoryId=gitlab-maven -Durl=https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/maven -DgroupId=nz.health.air.immsot -DartifactId=air-api-fhir-ig -Dversion=$MVN_IG_VERSION -Dpackaging=tgz

pages:
  image: alpine:latest
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == "main" || $CI_COMMIT_REF_NAME =~ /^release\/.+/
  before_script:
    - apk add curl unzip yq git
  script:
# Always use the scripts from main
    - rm -rf publish_scripts_tmp public
    - git clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/healthnz-prm/air/${PUBLISH_SCRIPTS_GIT_REPO}.git publish_scripts_tmp
    - (cd publish_scripts_tmp; sh ./ci-scripts/publish-website.sh)  
    - ls -T
  artifacts:
    paths:
      - public

ig-post-release:
  stage: post-release
  rules:
    - if: $RELEASE == "true"
  script:
    - ./ci-scripts/post-release.sh