name: Cut IG Release

#    uat   2.5.0-SNAPSHOT
#
#    Release workflow
#      + remove "-SNAPSHOT"
#      + commit
#      + create tag
#      + open rollup release PR
#      + bump uat to 2.6.0-SNAPSHOT
#
#    Merge release PR to main
#          |
#          v
#    main   2.5.0export YQ=/usr/bin/yq
#      on merge the publish runs

on:
  workflow_dispatch:
    inputs:
      major_version:
        description: 'Major version release'
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  cut_ig_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: function defs
        run: |
          echo "BASH_ENV=ci-scripts/function-defs.sh" >> "$GITHUB_ENV"

      - name: validate branch is uat/uat-V1
        run: | 
          echo "branch name ${{ github.ref_name }}"
          git remote -v
          if [[ ${{ github.ref_name }} != "uat" && ${{ github.ref_name }} != "uat-V1" ]]; then
            echo "release branch must be [uat|uat-V1]"
            exit 5
          fi  

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.RELEASE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          cat > ~/.ssh/config <<EOF
          Host github.com
            IdentityFile ~/.ssh/id_rsa
            IdentitiesOnly yes
          EOF          

      - name: install yq yaml parser
        run: |
          sudo wget --quiet https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq

      - name: snapshot to release version
        run: |
          git remote -v
          # It should look like:
          # origin  git@github.com:OWNER/REPO.git (fetch)
          # origin  git@github.com:OWNER/REPO.git (push)
          # If it says:
          # https://github.com/OWNER/REPO.git
          # then the deploy key will never be used.
          # Fix:
          git remote set-url origin git@github.com:OWNER/REPO.git

          export CI_COMMIT_BRANCH=${{ github.ref_name }}
          export RELEASE_MAJOR=${{ inputs.major_version }}
          ci-scripts/release.sh
